language: node_js
node_js:
  - lts/*
  - node
before_install:
  - 'git config --global url."git@github.com:".insteadOf "https://github.com/"'
  - npm i -g @labshare/lsc codecov
install:
  - npm install
script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codecov
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
